swagger: "2.0"
info:
  version: "0.0.1"
  title: "awsvm"
  description: "A service to use AWS virtual machine EC2 using swagger -2.0 specification and codegen"
  termsOfService: "http://swagger.io/terms/"
  contact:
    name: "Sushant Athaley"
  license:
    name: "Apache"
host: "localhost:8080"
basePath: "/api"
schemes:
  - "http"
consumes:
  - "application/json"
produces:
  - "application/json"
paths:
  /vms:
    get:
      description: "Returns list on VMs"
      produces:
        - "application/json"
      responses:
        "200":
          description: "VM Instances"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/VM"
  /vms/{vmId}:
    get:
      tags:
      - "vm"
      summary: "Find vm by ID"
      description: "Returns a single vm"
      operationId: "getVMById"
      produces:
        - "application/json"
      parameters:
      - name: "vmId"
        in: "path"
        description: "ID of VM to return"
        required: true
        type: "integer"
        format: "int64"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/VM"
        400:
          description: "Invalid ID supplied"
        404:
          description: "VM not found"
definitions:
  VM:
    type: "object"
    properties:
      vmId:
        type: "integer"
        format: "int64"
      name:
        type: "string"
      image:
        type: "string"
      location:
        type: "string"
      ramSize:
        type: "integer"
      diskSize:
        type: "integer"
      status:
        type: "string"
        description: "VM Status"
        enum:
        - "RUNNING"
        - "STARTING"
        - "REBOOTING"
        - "TERMINATED"
        - "STOPPING"
        - "STOPPED"
        - "PENDING"
        - "SUSPENDED"
        - "ERROR"
        - "PAUSED"
        - "RECONFIGURING"
        - "UNKNOWN"
